AMIZONE_ID = "AMIZONE ID HERE"
AMIZONE_PASSWORD = "AMIZONE PASSWORD HERE"
BOT_TOKEN = "BOT TOKEN HERE"
ADMINS_ID = ['ADMINS_ID_HERE_AS_INT']
GROUP_ID = 'GROUP_ID_HERE_AS_INT'  # Telegram group ID format starts from -100: add prefix -100 if not present
